/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as BasarilarRouteImport } from './routes/basarilar'
import { Route as SeviyelerRouteImport } from './routes/seviyeler'
import { Route as OynaLevelRouteImport } from './routes/oyna.$level'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const BasarilarRoute = BasarilarRouteImport.update({
  id: '/basarilar',
  path: '/basarilar',
  getParentRoute: () => rootRouteImport,
} as any)
const SeviyelerRoute = SeviyelerRouteImport.update({
  id: '/seviyeler',
  path: '/seviyeler',
  getParentRoute: () => rootRouteImport,
} as any)
const OynaLevelRoute = OynaLevelRouteImport.update({
  id: '/oyna/$level',
  path: '/oyna/$level',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/basarilar': typeof BasarilarRoute
  '/seviyeler': typeof SeviyelerRoute
  '/oyna/$level': typeof OynaLevelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/basarilar': typeof BasarilarRoute
  '/seviyeler': typeof SeviyelerRoute
  '/oyna/$level': typeof OynaLevelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/basarilar': typeof BasarilarRoute
  '/seviyeler': typeof SeviyelerRoute
  '/oyna/$level': typeof OynaLevelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ayarlar' | '/basarilar' | '/seviyeler' | '/oyna/$level'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ayarlar' | '/basarilar' | '/seviyeler' | '/oyna/$level'
  id:
    '__root__' | '/' | '/ayarlar' | '/basarilar' | '/seviyeler' | '/oyna/$level'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyarlarRoute: typeof AyarlarRoute
  BasarilarRoute: typeof BasarilarRoute
  SeviyelerRoute: typeof SeviyelerRoute
  OynaLevelRoute: typeof OynaLevelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basarilar': {
      id: '/basarilar'
      path: '/basarilar'
      fullPath: '/basarilar'
      preLoaderRoute: typeof BasarilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seviyeler': {
      id: '/seviyeler'
      path: '/seviyeler'
      fullPath: '/seviyeler'
      preLoaderRoute: typeof SeviyelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyna/$level': {
      id: '/oyna/$level'
      path: '/oyna/$level'
      fullPath: '/oyna/$level'
      preLoaderRoute: typeof OynaLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyarlarRoute: AyarlarRoute,
  BasarilarRoute: BasarilarRoute,
  SeviyelerRoute: SeviyelerRoute,
  OynaLevelRoute: OynaLevelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
